# 📊 Sales Forecasting Across Multiple Retail Stores
### --> NextHikes IT Solutions
### --> Project: Rossmann Pharmaceuticals
### --> Prepared by: Ankita Vaghela

# **Import Libraries**

In [1]:
import pandas as pd
import numpy as np
import logging
# from google.colab import files

This cell imports essential libraries like `pandas` for data manipulation, `numpy` for numerical operations, `logging` for tracking progress and debugging, and `files` from `google.colab` for file operations within the Colab environment.

# **Logger Configuration**

In [3]:
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)
logger.propagate = False

if not logger.handlers:
    console_handler = logging.StreamHandler()
    file_handler = logging.FileHandler('Project6_Preprocessing.log')
    formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')

    console_handler.setFormatter(formatter)
    file_handler.setFormatter(formatter)

    logger.addHandler(console_handler)
    logger.addHandler(file_handler)

logger.info("Project initialized and Logger set up successfully.")

2026-09-14 15:27:51,269 - INFO - Project initialized and Logger set up successfully.

This code block sets up a custom logger for the project. It configures the logger to display messages in the console and save them to a file named 'Project6_Preprocessing.log', ensuring that important events and debugging information are recorded.

==========================================================================================================

# **Preprocessing Store Data**

### **Data Loading**

In [4]:
logger.info("Loading Store Dataset")
df_store = pd.read_csv("store.csv")

2026-09-14 15:27:53,977 - INFO - Loading Store Dataset

This cell loads the `store.csv` dataset into a pandas DataFrame called `df_store`. This dataset contains information about the individual stores.

In [5]:
df_store.head()

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN

This command displays the first 5 rows of the `df_store` DataFrame, providing a quick preview of the data structure and content.

In [6]:
df_store.tail()

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
1110,1111,a,a,1900.0,6.0,2014.0,1,31.0,2013.0,"Jan,Apr,Jul,Oct"
1111,1112,c,c,1880.0,4.0,2006.0,0,NaN,NaN,NaN
1112,1113,a,c,9260.0,NaN,NaN,0,NaN,NaN,NaN
1113,1114,a,c,870.0,NaN,NaN,0,NaN,NaN,NaN
1114,1115,d,c,5350.0,NaN,NaN,1,22.0,2012.0,"Mar,Jun,Sept,Dec"

This command displays the last 5 rows of the `df_store` DataFrame, useful for checking the end of the dataset and ensuring data consistency.

In [7]:
df_store.info()

<class 'pandas.DataFrame'>
RangeIndex: 1115 entries, 0 to 1114
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Store                      1115 non-null   int64
 1   StoreType                  1115 non-null   str
 2   Assortment                 1115 non-null   str
 3   CompetitionDistance        1112 non-null   float64
 4   CompetitionOpenSinceMonth  761 non-null    float64
 5   CompetitionOpenSinceYear   761 non-null    float64
 6   Promo2                     1115 non-null   int64
 7   Promo2SinceWeek            571 non-null    float64
 8   Promo2SinceYear            571 non-null    float64
 9   PromoInterval              571 non-null    str
dtypes: float64(5), int64(2), str(3)
memory usage: 98.0 KB

This cell provides a concise summary of the `df_store` DataFrame, including the column names, non-null counts, data types, and memory usage. It's crucial for understanding the data's integrity and identifying potential issues like missing values.

### **Check Missing Value**

In [8]:
df_store.isnull().sum()

Store                          0
StoreType                      0
Assortment                     0
CompetitionDistance            3
CompetitionOpenSinceMonth    354
CompetitionOpenSinceYear     354
Promo2                         0
Promo2SinceWeek              544
Promo2SinceYear              544
PromoInterval                544
dtype: int64

This cell calculates and displays the total number of missing values for each column in the `df_store` DataFrame. This helps in identifying which columns require missing value imputation or handling.

### **Handle Missing Value**

In [9]:
df_store['CompetitionDistance'] = df_store['CompetitionDistance'].fillna(df_store['CompetitionDistance'].median())

df_store['CompetitionOpenSinceMonth'] = df_store['CompetitionOpenSinceMonth'].fillna(df_store['CompetitionOpenSinceMonth'].median())

df_store['CompetitionOpenSinceYear'] = df_store['CompetitionOpenSinceYear'].fillna(df_store['CompetitionOpenSinceYear'].median())

df_store['PromoInterval'] = df_store['PromoInterval'].fillna(df_store['PromoInterval'].mode())
df_store['Promo2SinceWeek'] = df_store['Promo2SinceWeek'].fillna(df_store['Promo2SinceWeek'].median())
df_store['Promo2SinceYear'] = df_store['Promo2SinceYear'].fillna(df_store['Promo2SinceYear'].median())

This cell handles missing values in `df_store` by imputing them. `CompetitionDistance`, `CompetitionOpenSinceMonth`, `CompetitionOpenSinceYear`, `Promo2SinceWeek`, and `Promo2SinceYear` are filled with their respective medians, while `PromoInterval` is filled with its mode. This ensures that all columns have complete data for further analysis.

### **Fixing Data Type**

In [10]:
df_store['Promo2SinceWeek'] = df_store['Promo2SinceWeek'].astype(int)
df_store['Promo2SinceYear'] = df_store['Promo2SinceYear'].astype(int)
df_store['CompetitionOpenSinceMonth'] = df_store['CompetitionOpenSinceMonth'].astype(int)
df_store['CompetitionOpenSinceYear'] = df_store['CompetitionOpenSinceYear'].astype(int)

This cell converts the data types of `Promo2SinceWeek`, `Promo2SinceYear`, `CompetitionOpenSinceMonth`, and `CompetitionOpenSinceYear` columns to integer type. This is done after filling missing values to ensure consistency and appropriate data representation.

### **Check Duplicate Value**

In [11]:
df_store.duplicated().sum()

np.int64(0)

This cell checks for any duplicate rows in the `df_store` DataFrame. The output indicates that there are no duplicate entries, ensuring data uniqueness.

In [12]:
logger.info("Preprocessing Store Dataset Completed")

2026-09-14 15:28:06,361 - INFO - Preprocessing Store Dataset Completed

This line logs a message confirming that the preprocessing steps for the `store` dataset have been successfully completed.

====================================================================================================
# **Preprocessing Train Data**

### **Data Loading**

In [13]:
logger.info("Loading Train Dataset")
df_train = pd.read_csv("train.csv",low_memory=False)

2026-09-14 15:28:08,919 - INFO - Loading Train Dataset

This cell loads the `train.csv` dataset into a pandas DataFrame called `df_train`. This dataset contains the historical sales data for the stores.

In [14]:
df_train.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,5,2015-07-31,5263,555,1,1,0,1
1,2,5,2015-07-31,6064,625,1,1,0,1
2,3,5,2015-07-31,8314,821,1,1,0,1
3,4,5,2015-07-31,13995,1498,1,1,0,1
4,5,5,2015-07-31,4822,559,1,1,0,1

This command displays the first 5 rows of the `df_train` DataFrame, providing a quick preview of the training data structure and content.

In [15]:
df_train.tail()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
1017204,1111,2,2013-01-01,0,0,0,0,a,1
1017205,1112,2,2013-01-01,0,0,0,0,a,1
1017206,1113,2,2013-01-01,0,0,0,0,a,1
1017207,1114,2,2013-01-01,0,0,0,0,a,1
1017208,1115,2,2013-01-01,0,0,0,0,a,1

This command displays the last 5 rows of the `df_train` DataFrame, useful for checking the end of the dataset and ensuring data consistency.

In [16]:
df_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 1017209 entries, 0 to 1017208
Data columns (total 9 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   Store          1017209 non-null  int64
 1   DayOfWeek      1017209 non-null  int64
 2   Date           1017209 non-null  str
 3   Sales          1017209 non-null  int64
 4   Customers      1017209 non-null  int64
 5   Open           1017209 non-null  int64
 6   Promo          1017209 non-null  int64
 7   StateHoliday   1017209 non-null  str
 8   SchoolHoliday  1017209 non-null  int64
dtypes: int64(7), str(2)
memory usage: 80.5 MB

This cell provides a concise summary of the `df_train` DataFrame, including the column names, non-null counts, data types, and memory usage. It's crucial for understanding the data's integrity and identifying potential issues like missing values.

### **Check Missing Value**

In [17]:
df_train.isnull().sum()

Store            0
DayOfWeek        0
Date             0
Sales            0
Customers        0
Open             0
Promo            0
StateHoliday     0
SchoolHoliday    0
dtype: int64

This cell calculates and displays the total number of missing values for each column in the `df_train` DataFrame. This helps in identifying which columns require missing value imputation or handling. In this case, there are no missing values.

### **Fixing Data Type**

In [18]:
df_train['Date'] = pd.to_datetime(df_train['Date'])
df_train['StateHoliday'] = df_train['StateHoliday'].astype(str)

This cell converts the 'Date' column in `df_train` to a datetime object, which is essential for time-series analysis. It also ensures the 'StateHoliday' column is treated as a string.

### **Check Duplicate Value**

In [19]:
df_train.duplicated().sum()

np.int64(0)

This cell checks for any duplicate rows in the `df_train` DataFrame. The output indicates that there are no duplicate entries, ensuring data uniqueness.

In [20]:
logger.info("Preprocessing Train Dataset Completed")

2026-09-14 15:28:19,849 - INFO - Preprocessing Train Dataset Completed

This line logs a message confirming that the preprocessing steps for the `train` dataset have been successfully completed.

==========================================================================================================

# **Preprocessing Test Data**

### **Data Loading**

In [21]:
logger.info("Loading Test Dataset")
df_test = pd.read_csv("test.csv")

2026-09-14 15:28:22,740 - INFO - Loading Test Dataset

This cell loads the `test.csv` dataset into a pandas DataFrame called `df_test`. This dataset contains the data for which sales predictions need to be made.

In [22]:
df_test.head()

   Id  Store  DayOfWeek        Date  Open  Promo StateHoliday  SchoolHoliday
0   1      1          4  2015-09-17   1.0      1            0              0
1   2      3          4  2015-09-17   1.0      1            0              0
2   3      7          4  2015-09-17   1.0      1            0              0
3   4      8          4  2015-09-17   1.0      1            0              0
4   5      9          4  2015-09-17   1.0      1            0              0

This command displays the first 5 rows of the `df_test` DataFrame, providing a quick preview of the test data structure and content.

In [23]:
df_test.tail()

,Id,Store,DayOfWeek,Date,Open,Promo,StateHoliday,SchoolHoliday
41083,41084,1111,6,2015-08-01,1.0,0,0,0
41084,41085,1112,6,2015-08-01,1.0,0,0,0
41085,41086,1113,6,2015-08-01,1.0,0,0,0
41086,41087,1114,6,2015-08-01,1.0,0,0,0
41087,41088,1115,6,2015-08-01,1.0,0,0,1

This command displays the last 5 rows of the `df_test` DataFrame, useful for checking the end of the dataset and ensuring data consistency.

In [24]:
df_test.info()

<class 'pandas.DataFrame'>
RangeIndex: 41088 entries, 0 to 41087
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             41088 non-null  int64
 1   Store          41088 non-null  int64
 2   DayOfWeek      41088 non-null  int64
 3   Date           41088 non-null  str
 4   Open           41077 non-null  float64
 5   Promo          41088 non-null  int64
 6   StateHoliday   41088 non-null  str
 7   SchoolHoliday  41088 non-null  int64
dtypes: float64(1), int64(5), str(2)
memory usage: 2.9 MB

This cell provides a concise summary of the `df_test` DataFrame, including the column names, non-null counts, data types, and memory usage. It's crucial for understanding the data's integrity and identifying potential issues like missing values.

### **Check Missing Value**

In [25]:
df_test.isnull().sum()

Id                0
Store             0
DayOfWeek         0
Date              0
Open             11
Promo             0
StateHoliday      0
SchoolHoliday     0
dtype: int64

This cell calculates and displays the total number of missing values for each column in the `df_test` DataFrame. This helps in identifying which columns require missing value imputation or handling.

### **Handle Missing Value**

In [26]:
df_test['Open'] = df_test['Open'].fillna(df_test['DayOfWeek'].apply(lambda x: 0 if x == 7 else 1))

This cell handles the missing values in the 'Open' column of `df_test`. It imputes 'Open' values based on the 'DayOfWeek' column: if the `DayOfWeek` is 7 (Sunday), 'Open' is set to 0 (closed); otherwise, it's set to 1 (open).

### **Fixing Data Type**

In [27]:
df_test['Open'] = df_test['Open'].astype(int)
df_test['Date'] = pd.to_datetime(df_test['Date'])
df_test['StateHoliday'] = df_test['StateHoliday'].astype(str)

This cell converts the 'Open' column to an integer type, the 'Date' column to a datetime object for time-series analysis, and ensures the 'StateHoliday' column is treated as a string in `df_test`.

### **Check Duplicate Value**

In [28]:
df_test.duplicated().sum()

np.int64(0)

This cell checks for any duplicate rows in the `df_test` DataFrame. The output indicates that there are no duplicate entries, ensuring data uniqueness.

In [29]:
logger.info("Preprocessing Test Dataset Completed")

2026-09-14 15:28:36,105 - INFO - Preprocessing Test Dataset Completed

This line logs a message confirming that the preprocessing steps for the `test` dataset have been successfully completed.

==========================================================================================================

# **Merge Store & Train Dataset**

In [30]:
logger.info("Merging Store and Train Dataset")
store_train = pd.merge(df_train, df_store, on='Store', how='left')
print("Train Merged Shape:",store_train.shape)

2026-09-14 15:28:40,048 - INFO - Merging Store and Train Dataset

Train Merged Shape: (1017209, 18)

This cell merges the `df_train` and `df_store` DataFrames into a new DataFrame called `store_train`. The merge is performed on the 'Store' column using a left join, combining store-specific information with the training sales data. It also prints the shape of the merged DataFrame.

# **Merge Store & Test Dataset**

In [31]:
logger.info("Merging Store and Test Dataset")
store_test = pd.merge(df_test, df_store, on='Store', how='left')
print("Test Merged Shape:",store_test.shape)

2026-09-14 15:28:43,433 - INFO - Merging Store and Test Dataset

Test Merged Shape: (41088, 17)

This cell merges the `df_test` and `df_store` DataFrames into a new DataFrame called `store_test`. Similar to the training data, this merges store-specific information with the test sales data for prediction. It also prints the shape of the merged DataFrame.

# **Saving Merged Dataset to CSV**

In [32]:
store_train.to_csv('store_train.csv', index=False)
store_test.to_csv('store_test.csv', index=False)
logger.info("Saving store_train & store_test dataset to CSV Successfully")

2026-09-14 15:28:50,105 - INFO - Saving store_train & store_test dataset to CSV Successfully

This cell saves the newly created `store_train` and `store_test` DataFrames to CSV files named 'store_train.csv' and 'store_test.csv' respectively. The `index=False` argument prevents pandas from writing the DataFrame index as a column in the CSV file. A log message confirms the successful saving.

# **Download Files**

In [ ]:
# files.download('store_train.csv')
# files.download('store_test.csv')
# logger.info("Download Both files Successfully")

2026-09-14 05:03:39,442 - INFO - Download Both files Successfully

This cell uses the `files.download` function from `google.colab` to prompt the user to download the 'store_train.csv' and 'store_test.csv' files to their local machine. A log message confirms the successful download prompt.